#!/bin/bash
VER="3.1.9-1"
DEST="dist"

mkdir -p $DEST

curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/aes.js -o $DEST/aes.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/aes.min.js -o $DEST/aes.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/aes.min.js.map -o $DEST/aes.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/aes.js -o $DEST/aes.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/aes.min.js -o $DEST/aes.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/aes.min.js.map -o $DEST/aes.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/cipher-core.js -o $DEST/cipher-core.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/cipher-core.min.js -o $DEST/cipher-core.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/cipher-core.min.js.map -o $DEST/cipher-core.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/core.js -o $DEST/core.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/core.min.js -o $DEST/core.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/core.min.js.map -o $DEST/core.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/crypto-js.js -o $DEST/crypto-js.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/crypto-js.min.js -o $DEST/crypto-js.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/crypto-js.min.js.map -o $DEST/crypto-js.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-base64.js -o $DEST/enc-base64.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-base64.min.js -o $DEST/enc-base64.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-base64.min.js.map -o $DEST/enc-base64.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-hex.js -o $DEST/enc-hex.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-hex.min.js -o $DEST/enc-hex.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-hex.min.js.map -o $DEST/enc-hex.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-latin1.js -o $DEST/enc-latin1.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-latin1.min.js -o $DEST/enc-latin1.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-latin1.min.js.map -o $DEST/enc-latin1.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-utf16.js -o $DEST/enc-utf16.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-utf16.min.js -o $DEST/enc-utf16.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-utf16.min.js.map -o $DEST/enc-utf16.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-utf8.js -o $DEST/enc-utf8.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-utf8.min.js -o $DEST/enc-utf8.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/enc-utf8.min.js.map -o $DEST/enc-utf8.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/evpkdf.js -o $DEST/evpkdf.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/evpkdf.min.js -o $DEST/evpkdf.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/evpkdf.min.js.map -o $DEST/evpkdf.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/format-hex.js -o $DEST/format-hex.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/format-hex.min.js -o $DEST/format-hex.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/format-hex.min.js.map -o $DEST/format-hex.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/format-openssl.js -o $DEST/format-openssl.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/format-openssl.min.js -o $DEST/format-openssl.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/format-openssl.min.js.map -o $DEST/format-openssl.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-md5.js -o $DEST/hmac-md5.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-md5.min.js -o $DEST/hmac-md5.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-md5.min.js.map -o $DEST/hmac-md5.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-ripemd160.js -o $DEST/hmac-ripemd160.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-ripemd160.min.js -o $DEST/hmac-ripemd160.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-ripemd160.min.js.map -o $DEST/hmac-ripemd160.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha1.js -o $DEST/hmac-sha1.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha1.min.js -o $DEST/hmac-sha1.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha1.min.js.map -o $DEST/hmac-sha1.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha224.js -o $DEST/hmac-sha224.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha224.min.js -o $DEST/hmac-sha224.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha224.min.js.map -o $DEST/hmac-sha224.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha256.js -o $DEST/hmac-sha256.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha256.min.js -o $DEST/hmac-sha256.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha256.min.js.map -o $DEST/hmac-sha256.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha3.js -o $DEST/hmac-sha3.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha3.min.js -o $DEST/hmac-sha3.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha3.min.js.map -o $DEST/hmac-sha3.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha384.js -o $DEST/hmac-sha384.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha384.min.js -o $DEST/hmac-sha384.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha384.min.js.map -o $DEST/hmac-sha384.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha512.js -o $DEST/hmac-sha512.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha512.min.js -o $DEST/hmac-sha512.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac-sha512.min.js.map -o $DEST/hmac-sha512.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac.js -o $DEST/hmac.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac.min.js -o $DEST/hmac.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/hmac.min.js.map -o $DEST/hmac.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/index.js -o $DEST/index.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/index.min.js -o $DEST/index.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/index.min.js.map -o $DEST/index.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/lib-typedarrays.js -o $DEST/lib-typedarrays.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/lib-typedarrays.min.js -o $DEST/lib-typedarrays.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/lib-typedarrays.min.js.map -o $DEST/lib-typedarrays.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/md5.js -o $DEST/md5.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/md5.min.js -o $DEST/md5.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/md5.min.js.map -o $DEST/md5.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-cfb.js -o $DEST/mode-cfb.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-cfb.min.js -o $DEST/mode-cfb.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-cfb.min.js.map -o $DEST/mode-cfb.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ctr-gladman.js -o $DEST/mode-ctr-gladman.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ctr-gladman.min.js -o $DEST/mode-ctr-gladman.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ctr-gladman.min.js.map -o $DEST/mode-ctr-gladman.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ctr.js -o $DEST/mode-ctr.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ctr.min.js -o $DEST/mode-ctr.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ctr.min.js.map -o $DEST/mode-ctr.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ecb.js -o $DEST/mode-ecb.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ecb.min.js -o $DEST/mode-ecb.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ecb.min.js.map -o $DEST/mode-ecb.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ofb.js -o $DEST/mode-ofb.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ofb.min.js -o $DEST/mode-ofb.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/mode-ofb.min.js.map -o $DEST/mode-ofb.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-ansix923.js -o $DEST/pad-ansix923.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-ansix923.min.js -o $DEST/pad-ansix923.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-ansix923.min.js.map -o $DEST/pad-ansix923.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-iso10126.js -o $DEST/pad-iso10126.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-iso10126.min.js -o $DEST/pad-iso10126.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-iso10126.min.js.map -o $DEST/pad-iso10126.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-iso97971.js -o $DEST/pad-iso97971.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-iso97971.min.js -o $DEST/pad-iso97971.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-iso97971.min.js.map -o $DEST/pad-iso97971.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-nopadding.js -o $DEST/pad-nopadding.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-nopadding.min.js -o $DEST/pad-nopadding.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-nopadding.min.js.map -o $DEST/pad-nopadding.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-pkcs7.js -o $DEST/pad-pkcs7.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-pkcs7.min.js -o $DEST/pad-pkcs7.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-pkcs7.min.js.map -o $DEST/pad-pkcs7.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-zeropadding.js -o $DEST/pad-zeropadding.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-zeropadding.min.js -o $DEST/pad-zeropadding.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pad-zeropadding.min.js.map -o $DEST/pad-zeropadding.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pbkdf2.js -o $DEST/pbkdf2.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pbkdf2.min.js -o $DEST/pbkdf2.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/pbkdf2.min.js.map -o $DEST/pbkdf2.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rabbit-legacy.js -o $DEST/rabbit-legacy.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rabbit-legacy.min.js -o $DEST/rabbit-legacy.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rabbit-legacy.min.js.map -o $DEST/rabbit-legacy.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rabbit.js -o $DEST/rabbit.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rabbit.min.js -o $DEST/rabbit.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rabbit.min.js.map -o $DEST/rabbit.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rc4.js -o $DEST/rc4.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rc4.min.js -o $DEST/rc4.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/rc4.min.js.map -o $DEST/rc4.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/ripemd160.js -o $DEST/ripemd160.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/ripemd160.min.js -o $DEST/ripemd160.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/ripemd160.min.js.map -o $DEST/ripemd160.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha1.js -o $DEST/sha1.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha1.min.js -o $DEST/sha1.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha1.min.js.map -o $DEST/sha1.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha224.js -o $DEST/sha224.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha224.min.js -o $DEST/sha224.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha224.min.js.map -o $DEST/sha224.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha256.js -o $DEST/sha256.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha256.min.js -o $DEST/sha256.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha256.min.js.map -o $DEST/sha256.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha3.js -o $DEST/sha3.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha3.min.js -o $DEST/sha3.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha3.min.js.map -o $DEST/sha3.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha384.js -o $DEST/sha384.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha384.min.js -o $DEST/sha384.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha384.min.js.map -o $DEST/sha384.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha512.js -o $DEST/sha512.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha512.min.js -o $DEST/sha512.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/sha512.min.js.map -o $DEST/sha512.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/tripledes.js -o $DEST/tripledes.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/tripledes.min.js -o $DEST/tripledes.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/tripledes.min.js.map -o $DEST/tripledes.min.js.map
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/x64-core.js -o $DEST/x64-core.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/x64-core.min.js -o $DEST/x64-core.min.js
curl https://cdnjs.cloudflare.com/ajax/libs/crypto-js/$VER/x64-core.min.js.map -o $DEST/x64-core.min.js.map
